#!/usr/bin/env bash
# Deploy the MCPbox Worker to Cloudflare with the correct VPC service binding.
#
# This script fetches the active Cloudflare configuration from the backend,
# generates worker/wrangler.toml with the correct VPC service ID, and deploys
# the Worker using wrangler.
#
# Usage:
#   ./scripts/deploy-worker.sh               # Deploy only
#   ./scripts/deploy-worker.sh --set-secrets  # Deploy and set Worker secrets
#
# Prerequisites:
#   - Backend running (docker compose up -d)
#   - Active Cloudflare config (wizard completed through step 3+)
#   - Node.js/npm installed (for wrangler)
#   - Authenticated with Cloudflare (npx wrangler login)

set -euo pipefail

BACKEND_URL="${BACKEND_URL:-http://localhost:8000}"
SANDBOX_API_KEY="${SANDBOX_API_KEY:?SANDBOX_API_KEY is required for internal API auth}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKER_DIR="$(cd "$SCRIPT_DIR/../worker" && pwd)"
SET_SECRETS=false
AUTH_HEADER="Authorization: Bearer $SANDBOX_API_KEY"

for arg in "$@"; do
    case "$arg" in
        --set-secrets) SET_SECRETS=true ;;
        *) echo "Unknown argument: $arg"; exit 1 ;;
    esac
done

echo "==> Fetching worker deployment config from backend..."
RESPONSE=$(curl -sf -H "$AUTH_HEADER" "$BACKEND_URL/internal/worker-deploy-config" 2>&1) || {
    echo "ERROR: Could not reach backend at $BACKEND_URL"
    echo "Make sure the backend is running: docker compose up -d"
    exit 1
}

# Check for error response
ERROR=$(echo "$RESPONSE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('error',''))" 2>/dev/null)
if [ -n "$ERROR" ]; then
    echo "ERROR: $ERROR"
    exit 1
fi

# Extract config values
VPC_SERVICE_ID=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['vpc_service_id'])")
WORKER_NAME=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['worker_name'])")
TEAM_DOMAIN=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('team_domain') or '')")
MCP_PORTAL_AUD=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('mcp_portal_aud') or '')")
MCP_PORTAL_HOSTNAME=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('mcp_portal_hostname') or '')")
KV_NAMESPACE_ID=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('kv_namespace_id') or '')")

echo "    Worker name:     $WORKER_NAME"
echo "    VPC service ID:  $VPC_SERVICE_ID"
echo "    KV namespace ID: ${KV_NAMESPACE_ID:-'(not set)'}"
echo "    Team domain:     ${TEAM_DOMAIN:-'(not set)'}"
echo "    MCP Portal AUD:  ${MCP_PORTAL_AUD:0:16}${MCP_PORTAL_AUD:+...}"
echo "    Portal hostname: ${MCP_PORTAL_HOSTNAME:-'(not set)'}"

echo ""
echo "==> Generating worker/wrangler.toml..."

# Create KV namespace if not yet created
if [ -z "$KV_NAMESPACE_ID" ]; then
    echo ""
    echo "==> Creating KV namespace for OAuth..."
    KV_OUTPUT=$(npx wrangler kv namespace create OAUTH_KV 2>&1)
    KV_NAMESPACE_ID=$(echo "$KV_OUTPUT" | python3 -c "import sys,re; m=re.search(r'id\s*=\s*\"([^\"]+)\"', sys.stdin.read()); print(m.group(1) if m else '')" 2>/dev/null)
    if [ -z "$KV_NAMESPACE_ID" ]; then
        echo "    ERROR: Could not create KV namespace"
        echo "    Output: $KV_OUTPUT"
        exit 1
    fi
    echo "    Created KV namespace: $KV_NAMESPACE_ID"
fi

cat > "$WORKER_DIR/wrangler.toml" << EOF
# MCPbox MCP Proxy Worker (generated by scripts/deploy-worker.sh)
# Do not edit manually - re-run the deploy script to regenerate.
name = "$WORKER_NAME"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Workers VPC Service binding for private tunnel access
[[vpc_services]]
binding = "MCPBOX_TUNNEL"
service_id = "$VPC_SERVICE_ID"

# KV namespace for OAuth token/grant storage
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "$KV_NAMESPACE_ID"
EOF

echo "    Generated: $WORKER_DIR/wrangler.toml"

echo ""
echo "==> Installing dependencies..."
cd "$WORKER_DIR"
npm install --production

echo ""
echo "==> Deploying Worker..."
npx wrangler deploy

if [ "$SET_SECRETS" = true ]; then
    echo ""
    echo "==> Setting Worker secrets..."

    # Fetch service token from backend database
    echo "    Fetching service token from backend..."
    TOKEN_RESPONSE=$(curl -sf -H "$AUTH_HEADER" "$BACKEND_URL/internal/active-service-token" 2>&1) || {
        echo "    WARNING: Could not fetch service token from backend"
        TOKEN_RESPONSE=""
    }

    if [ -n "$TOKEN_RESPONSE" ]; then
        SERVICE_TOKEN=$(echo "$TOKEN_RESPONSE" | python3 -c "import sys,json; t=json.load(sys.stdin).get('token'); print(t or '')" 2>/dev/null)
        if [ -n "$SERVICE_TOKEN" ]; then
            echo "$SERVICE_TOKEN" | npx wrangler secret put MCPBOX_SERVICE_TOKEN
            echo "    Set MCPBOX_SERVICE_TOKEN"
        else
            echo "    Skipping MCPBOX_SERVICE_TOKEN (no active service token in database)"
        fi
    fi

    if [ -n "$TEAM_DOMAIN" ]; then
        echo "$TEAM_DOMAIN" | npx wrangler secret put CF_ACCESS_TEAM_DOMAIN
        echo "    Set CF_ACCESS_TEAM_DOMAIN"
    else
        echo "    Skipping CF_ACCESS_TEAM_DOMAIN (not configured)"
    fi

    if [ -n "$MCP_PORTAL_AUD" ]; then
        echo "$MCP_PORTAL_AUD" | npx wrangler secret put CF_ACCESS_AUD
        echo "    Set CF_ACCESS_AUD"
    else
        echo "    Skipping CF_ACCESS_AUD (not configured)"
    fi

    if [ -n "$MCP_PORTAL_HOSTNAME" ]; then
        echo "$MCP_PORTAL_HOSTNAME" | npx wrangler secret put MCP_PORTAL_HOSTNAME
        echo "    Set MCP_PORTAL_HOSTNAME"
    else
        echo "    Skipping MCP_PORTAL_HOSTNAME (not configured)"
    fi
fi

echo ""
echo "==> Done! Worker deployed successfully."
echo "    URL: https://$WORKER_NAME.workers.dev"
