#!/usr/bin/env bash
# Deploy the MCPbox Worker to Cloudflare with the correct VPC service binding.
#
# This script fetches the active Cloudflare configuration from the backend,
# generates worker/wrangler.toml with the correct VPC service ID, and deploys
# the Worker using wrangler.
#
# Usage:
#   ./scripts/deploy-worker.sh               # Deploy only
#   ./scripts/deploy-worker.sh --set-secrets  # Deploy and set Worker secrets
#
# Prerequisites:
#   - Backend running (docker compose up -d)
#   - Active Cloudflare config (wizard completed through step 3+)
#   - Node.js/npm installed (for wrangler)
#   - Authenticated with Cloudflare (npx wrangler login)

set -euo pipefail

BACKEND_URL="${BACKEND_URL:-http://localhost:8000}"
SANDBOX_API_KEY="${SANDBOX_API_KEY:?SANDBOX_API_KEY is required for internal API auth}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKER_DIR="$(cd "$SCRIPT_DIR/../worker" && pwd)"
SET_SECRETS=false
AUTH_HEADER="Authorization: Bearer $SANDBOX_API_KEY"

for arg in "$@"; do
    case "$arg" in
        --set-secrets) SET_SECRETS=true ;;
        *) echo "Unknown argument: $arg"; exit 1 ;;
    esac
done

echo "==> Fetching worker deployment config from backend..."
RESPONSE=$(curl -sf -H "$AUTH_HEADER" "$BACKEND_URL/internal/worker-deploy-config" 2>&1) || {
    echo "ERROR: Could not reach backend at $BACKEND_URL"
    echo "Make sure the backend is running: docker compose up -d"
    exit 1
}

# Check for error response
ERROR=$(echo "$RESPONSE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('error',''))" 2>/dev/null)
if [ -n "$ERROR" ]; then
    echo "ERROR: $ERROR"
    exit 1
fi

# Extract config values
VPC_SERVICE_ID=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['vpc_service_id'])")
WORKER_NAME=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['worker_name'])")
KV_NAMESPACE_ID=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('kv_namespace_id') or '')")
# Access for SaaS OIDC credentials
ACCESS_CLIENT_ID=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('access_client_id') or '')")
ACCESS_CLIENT_SECRET=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('access_client_secret') or '')")
ACCESS_TOKEN_URL=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('access_token_url') or '')")
ACCESS_AUTHORIZATION_URL=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('access_authorization_url') or '')")
ACCESS_JWKS_URL=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('access_jwks_url') or '')")

echo "    Worker name:       $WORKER_NAME"
echo "    VPC service ID:    $VPC_SERVICE_ID"
echo "    KV namespace ID:   ${KV_NAMESPACE_ID:-'(not set)'}"
echo "    Access Client ID:  ${ACCESS_CLIENT_ID:0:16}${ACCESS_CLIENT_ID:+...}"
echo "    OIDC Token URL:    ${ACCESS_TOKEN_URL:-'(not set)'}"
echo "    OIDC Auth URL:     ${ACCESS_AUTHORIZATION_URL:-'(not set)'}"
echo "    OIDC JWKS URL:     ${ACCESS_JWKS_URL:-'(not set)'}"

echo ""
echo "==> Generating worker/wrangler.toml..."

# Create KV namespace if not yet created
if [ -z "$KV_NAMESPACE_ID" ]; then
    echo ""
    echo "==> Creating KV namespace for OAuth..."
    KV_OUTPUT=$(npx wrangler kv namespace create OAUTH_KV 2>&1)
    KV_NAMESPACE_ID=$(echo "$KV_OUTPUT" | python3 -c "import sys,re; m=re.search(r'id\s*=\s*\"([^\"]+)\"', sys.stdin.read()); print(m.group(1) if m else '')" 2>/dev/null)
    if [ -z "$KV_NAMESPACE_ID" ]; then
        echo "    ERROR: Could not create KV namespace"
        echo "    Output: $KV_OUTPUT"
        exit 1
    fi
    echo "    Created KV namespace: $KV_NAMESPACE_ID"
fi

cat > "$WORKER_DIR/wrangler.toml" << EOF
# MCPbox MCP Proxy Worker (generated by scripts/deploy-worker.sh)
# Do not edit manually - re-run the deploy script to regenerate.
name = "$WORKER_NAME"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Workers VPC Service binding for private tunnel access
[[vpc_services]]
binding = "MCPBOX_TUNNEL"
service_id = "$VPC_SERVICE_ID"

# KV namespace for OAuth token/grant storage
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "$KV_NAMESPACE_ID"
EOF

echo "    Generated: $WORKER_DIR/wrangler.toml"

echo ""
echo "==> Installing dependencies..."
cd "$WORKER_DIR"
npm install --production

echo ""
echo "==> Deploying Worker..."
npx wrangler deploy

if [ "$SET_SECRETS" = true ]; then
    echo ""
    echo "==> Setting Worker secrets..."

    # Fetch service token from backend database
    echo "    Fetching service token from backend..."
    TOKEN_RESPONSE=$(curl -sf -H "$AUTH_HEADER" "$BACKEND_URL/internal/active-service-token" 2>&1) || {
        echo "    WARNING: Could not fetch service token from backend"
        TOKEN_RESPONSE=""
    }

    if [ -n "$TOKEN_RESPONSE" ]; then
        SERVICE_TOKEN=$(echo "$TOKEN_RESPONSE" | python3 -c "import sys,json; t=json.load(sys.stdin).get('token'); print(t or '')" 2>/dev/null)
        if [ -n "$SERVICE_TOKEN" ]; then
            echo "$SERVICE_TOKEN" | npx wrangler secret put MCPBOX_SERVICE_TOKEN
            echo "    Set MCPBOX_SERVICE_TOKEN"
        else
            echo "    Skipping MCPBOX_SERVICE_TOKEN (no active service token in database)"
        fi
    fi

    # Access for SaaS OIDC credentials
    if [ -n "$ACCESS_CLIENT_ID" ]; then
        echo "$ACCESS_CLIENT_ID" | npx wrangler secret put ACCESS_CLIENT_ID
        echo "    Set ACCESS_CLIENT_ID"
    else
        echo "    Skipping ACCESS_CLIENT_ID (not configured)"
    fi

    if [ -n "$ACCESS_CLIENT_SECRET" ]; then
        echo "$ACCESS_CLIENT_SECRET" | npx wrangler secret put ACCESS_CLIENT_SECRET
        echo "    Set ACCESS_CLIENT_SECRET"
    else
        echo "    Skipping ACCESS_CLIENT_SECRET (not configured)"
    fi

    if [ -n "$ACCESS_TOKEN_URL" ]; then
        echo "$ACCESS_TOKEN_URL" | npx wrangler secret put ACCESS_TOKEN_URL
        echo "    Set ACCESS_TOKEN_URL"
    else
        echo "    Skipping ACCESS_TOKEN_URL (not configured)"
    fi

    if [ -n "$ACCESS_AUTHORIZATION_URL" ]; then
        echo "$ACCESS_AUTHORIZATION_URL" | npx wrangler secret put ACCESS_AUTHORIZATION_URL
        echo "    Set ACCESS_AUTHORIZATION_URL"
    else
        echo "    Skipping ACCESS_AUTHORIZATION_URL (not configured)"
    fi

    if [ -n "$ACCESS_JWKS_URL" ]; then
        echo "$ACCESS_JWKS_URL" | npx wrangler secret put ACCESS_JWKS_URL
        echo "    Set ACCESS_JWKS_URL"
    else
        echo "    Skipping ACCESS_JWKS_URL (not configured)"
    fi

    # Generate and set cookie encryption key
    COOKIE_KEY=$(openssl rand -hex 32)
    echo "$COOKIE_KEY" | npx wrangler secret put COOKIE_ENCRYPTION_KEY
    echo "    Set COOKIE_ENCRYPTION_KEY"
fi

echo ""
echo "==> Done! Worker deployed successfully."
echo "    URL: https://$WORKER_NAME.workers.dev"
